### ISSUE TITLE
Not Getting Stack Traces in Airbrake

### ISSUE THREAD

**Issue by micah-williamson** [airbrake/log4javabrake2#8]
I am trying to get stack traces to send to airbrake. This works fine when using the Notifier directly, but the stack trace is lost when using log4j. My log4j looks like this-

```
<Appenders>
        <Console name="ConsoleAppender" target="SYSTEM_OUT">
            <PatternLayout pattern="%d{YYYY-MM-dd HH:mm:ss} [%t] %-5p %c:%L - %m%n" />
        </Console>

        <Airbrake name="Airbrake"
                  projectId="${env:AIRBRAKE_PROJECT_ID}"
                  projectKey="${env:AIRBRAKE_PROJECT_KEY}"
                  env="production">
            <LevelRangeFilter minLevel="ERROR" />
        </Airbrake>
    </Appenders>

    <Loggers>
        <Root>
            <AppenderRef ref="Airbrake" />
        </Root>

        <Logger name="com.acme.foo" level="${env:LOG_LEVEL:-ERROR}">
            <AppenderRef ref="ConsoleAppender" />
        </Logger>
    </Loggers>
```

How can I configure log4javabrake2 to send stack traces?

**Comment by vmihailenco** [comment]
Well, looking at the code backtrace is available in 2 cases
- when there is a `throwable` - https://github.com/airbrake/log4javabrake2/blob/master/src/main/java/AirbrakeAppender.java#L71-L80
- or `source` - https://github.com/airbrake/log4javabrake2/blob/master/src/main/java/AirbrakeAppender.java#L86-L89

Otherwise backtrace is not available because there is no information from log4j. I am not sure what we can do here...

**Comment by micah-williamson** [comment]
It was to do with the way I was passing the error. 

`logger.error(myError)` does not send backtraces.
`logger.error("Oh no!", myError)` does send backtraces.

Not sure if that was intended.

**Comment by sumitjoshi1989** [comment]
It’s working with both scenarios in newer version of log4javabrake2. Please have a look.
